name: CI/CD

on:
  push:
    branches: 
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "dev"

    - name: Cache Composer dependencies
      uses: docker-practice/actions-setup-docker@master
      
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t my-app .
        docker push my-app:latest
        
  test:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run tests
      run: |
        docker run my-app:latest pytest
        
  deploy:
    # needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production
      env:
        HOST_SSH_USERNAME: ${{ secrets.HOST_SSH_USERNAME }}
        HOST_SSH_PASSWORD: ${{ secrets.HOST_SSH_PASSWORD }}
      run: |
        ssh $HOST_SSH_USERNAME@example.com "docker pull my-app:latest && docker run -d my-app:latest"